[tox]
envlist = pytest{7}-py{37,310}
skip_missing_interpreters = true

[testenv]
deps =
    --index-url=https://artifactory.devinfra.drdev.io/artifactory/api/pypi/python-all/simple
    pytest7: pytest>=7.0.0,<8.0.0
